package com.gardify.android.ui.agb;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.webkit.WebView;
import android.widget.ProgressBar;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

import com.gardify.android.R;
import com.gardify.android.utils.UiUtils;

import static com.gardify.android.utils.UiUtils.setupToolbar;

public class AgbFragment extends Fragment {


    public View onCreateView(@NonNull LayoutInflater inflater,
                             ViewGroup container, Bundle savedInstanceState) {

        View root = inflater.inflate(R.layout.fragment_agb, container, false);

        setupToolbar(getActivity(), "AGB", R.drawable.gardify_icon, R.color.colorPrimary,true);
        init(root);

        return root;
    }

    public void init(View root) {
        WebView webView = root.findViewById(R.id.web_view_agb_body);
        ProgressBar progressBar = root.findViewById(R.id.progressBar_agb);

        String htmlString2 = "<div _ngcontent-umy-c112=\"\" class=\"container pt-3 pb-5\"><div _ngcontent-umy-c112=\"\" class=\"row mt-5 mb-4\"><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h2 _ngcontent-umy-c112=\"\" class=\"t-light t-26\">Allgemeine Geschäftsbedingungen (AGB) der Becker Joest Volk Verlag GmbH &amp; Co. KG</h2></div></div><div _ngcontent-umy-c112=\"\" class=\"row\"><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs1\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 1 Geltungsbereich</h3><p _ngcontent-umy-c112=\"\">Für die Geschäftsbeziehung zwischen der Becker Joest Volk Verlag GmbH &amp; Co. KG (im Folgenden: Verkäufer) und dem Besteller gelten ausschließlich – auch für alle zukünftigen Geschäfte – die nachfolgenden allgemeinen Geschäftsbedingungen in ihrer zum Zeitpunkt der Bestellung gültigen Fassung. Abweichende Bedingungen des Bestellers erkennt der Verkäufer nicht an, es sei denn, er hat ausdrücklich ihrer Geltung zugestimmt. </p><p _ngcontent-umy-c112=\"\"> " +
                "Für Produkte, die auf Gardify.de über andere Shops angeboten werden, gelten ausschließlich deren Bestell- und Rücksendebedingungen und deren AGBs. </p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs2\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 2 Vertragsschluss</h3><p _ngcontent-umy-c112=\"\">Ihre Bestellung wird ausgelöst, wenn Sie die Ware in den Warenkorb gelegt haben und auf „Kaufen“ klicken. Mit der Bestellung erklären Sie verbindlich, die Ware erwerben zu wollen. Sie werden über den Eingang Ihrer Bestellung umgehend per E-Mail informiert. Die Zugangsbestätigung erfolgt automatisch und stellt noch keine Annahmeerklärung dar. Der Kaufvertrag kommt dadurch zustande, dass wir das in Ihrer Bestellung liegende Angebot zum Abschluss eines Kaufvertrags durch Lieferung der Ware annehmen. </p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs3\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 3 Widerrufsrecht</h3>" +
                "<p _ngcontent-umy-c112=\"\">Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.</p><p _ngcontent-umy-c112=\"\"> Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Waren (oder die letzte Ware oder die letzte Teilsendung oder das letzte Stück im Falle eines Vertrags über mehrere Waren, die der Verbraucher im Rahmen einer einheitlichen Bestellung bestellt hat und die getrennt geliefert werden sowie im Falle eines Vertrags über die Lieferung einer Ware in mehreren Teilsendungen oder Stücken) in Besitz genommen haben bzw. hat. </p><p _ngcontent-umy-c112=\"\">Um Ihr Widerrufsrecht auszuüben, müssen Sie uns</p><p _ngcontent-umy-c112=\"\"> BECKER JOEST VOLK VERLAG GmbH &amp; Co. KG <br _ngcontent-umy-c112=\"\"> Bahnhofsallee 5 <br _ngcontent-umy-c112=\"\"> 40721 Hilden <br _ngcontent-umy-c112=\"\"><br _ngcontent-umy-c112=\"\"> Telefon 0 21 03 – 9 07 88 0 <br _ngcontent-umy-c112=\"\"> Fax 0 21 03 – 9 07 88 28 <br _ngcontent-umy-c112=\"\">" +
                " E-Mail: info@bjvv.de <br _ngcontent-umy-c112=\"\"></p><p _ngcontent-umy-c112=\"\"> mittels einer eindeutigen Erklärung (z. B. ein mit der Post versandter Brief, Telefax oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist. </p><p _ngcontent-umy-c112=\"\"> Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden. </p><br _ngcontent-umy-c112=\"\"><p _ngcontent-umy-c112=\"\"><strong _ngcontent-umy-c112=\"\">Folgen des Widerrufs</strong></p><p _ngcontent-umy-c112=\"\">Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), " +
                "unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist. </p><p _ngcontent-umy-c112=\"\"> Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen vierzehn Tagen ab dem Tag, an dem Sie uns über den Widerruf dieses Vertrags unterrichten, an LKG Kommissions- und Abrechnungsgesellschaft mbH, An der Südspitze 1–12, 04571 Rötha zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von vierzehn Tagen absenden. </p><p _ngcontent-umy-c112=\"\">" +
                "Wir tragen die Kosten der Rücksendung der Waren wie folgt: </p><p _ngcontent-umy-c112=\"\">Für Rücksendungen aus Deutschland wird ein Pauschalbetrag in Höhe von 4,95 € erstattet. Für Rücksendungen aus Österreich wird ein Pausschalbetrag in Höhe von 9,95 € erstattet. Sollten Ihnen höhere Rücksendekosten als die Pauschalbeträge entstehen, werden Ihnen diese höheren Kosten erstattet, wenn Sie einen entsprechenden Zahlungsnachweis mit in das Paket hineinlegen.</p><p _ngcontent-umy-c112=\"\">Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.</p><p _ngcontent-umy-c112=\"\"><strong _ngcontent-umy-c112=\"\">Ausnahmen vom Widerrufsrecht</strong></p><p _ngcontent-umy-c112=\"\">Das Widerrufsrecht besteht nicht bzw. erlischt bei folgenden Verträgen: </p><p _ngcontent-umy-c112=\"\"> - Verträge zur Lieferung von Zeitungen, Zeitschriften oder Illustrierten mit Ausnahme von Abonnement-Verträgen.</p><p _ngcontent-umy-c112=\"\">" +
                "<strong _ngcontent-umy-c112=\"\">Ende der Widerrufsbelehrung</strong></p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs4\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 4 Vorbehalt der Nichtverfügbarkeit</h3><p _ngcontent-umy-c112=\"\">Wir behalten uns vor, von einer Ausführung Ihrer Bestellung abzusehen, wenn wir den bestellten Titel nicht vorrätig haben, der nicht vorrätige Titel vergriffen und die bestellte Ware infolgedessen nicht verfügbar ist. In diesem Fall werden wir Sie unverzüglich über die Nichtverfügbarkeit informieren und einen gegebenenfalls von Ihnen bereits gezahlten Kaufpreis unverzüglich rückerstatten.</p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs5\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 5 Preise und Versandkosten, Lieferung in andere Länder</h3><p _ngcontent-umy-c112=\"\">Unsere Preise sind Endpreise in Euro. Sie enthalten die gesetzliche Mehrwertsteuer.</p><p _ngcontent-umy-c112=\"\"><strong _ngcontent-umy-c112=\"\">" +
                "Versandbedingungen</strong> Die Lieferung der Ware erfolgt weltweit. <br _ngcontent-umy-c112=\"\"> Versandkostenangaben sind inklusive gesetzliche Mehrwertsteuer. <strong _ngcontent-umy-c112=\"\">Lieferungen im Inland (Deutschland):</strong> Wir berechnen die Versandkosten pauschal mit 4,95 € pro Bestellung. <br _ngcontent-umy-c112=\"\"> Bei der Versendung sperriger Güter (Speditionsversand) berechnen wir wie folgt: <br _ngcontent-umy-c112=\"\"> Luftpolsterfolien und Sperrgüter werden per Spedition oder DHL Großpaket versendet – 4,95 € je Artikel. Bei einem Gesamtwarenwert von über 50,- € fallen keine Versandkosten an. Ausgenommen sind Sperrgutlieferungen. Diese sind unter der Artikelbeschreibung gekennzeichnet. <br _ngcontent-umy-c112=\"\"> Sperrige Güter sind als solche in der Artikelbeschreibung gekennzeichnet. <strong _ngcontent-umy-c112=\"\">Lieferungen ins Ausland:</strong> Eine Lieferung ins Ausland erfolgt nicht bzw. nur nach schriftlichem Angebot.<br _ngcontent-umy-c112=\"\"><br _ngcontent-umy-c112=\"\"> Wir berechnen die Versandkosten ins Ausland nach Versandgewicht: <br _ngcontent-umy-c112=\"\">" +
                " Österreich pauschal 9,90 € <br _ngcontent-umy-c112=\"\"> Weltweit / Europa / EU: <br _ngcontent-umy-c112=\"\"> Die Versandkosten können bei Bestellungen aus dem Ausland per Kontaktformular angefragt werden. <br _ngcontent-umy-c112=\"\"><strong _ngcontent-umy-c112=\"\">Lieferfristen</strong> Soweit im jeweiligen Angebot keine andere Frist angegeben ist, erfolgt die Lieferung der Ware im Inland (Deutschland) innerhalb von 2 - 10 Tagen, bei Auslandslieferungen innerhalb von 3 - 30 Tagen nach Vertragsschluss (bei vereinbarter Vorauszahlung nach dem Zeitpunkt Ihrer Zahlungsanweisung). Beachten Sie, dass an Sonn- und Feiertagen keine Zustellung erfolgt. Haben Sie Artikel mit unterschiedlichen Lieferzeiten bestellt, versenden wir die Ware in einer gemeinsamen Sendung, sofern wir keine abweichenden Vereinbarungen mit Ihnen getroffen haben. Die Lieferzeit bestimmt sich in diesem Fall nach dem Artikel mit der längsten Lieferzeit den Sie bestellt haben.Der Mindestbestellwert beträgt: 10 €. <strong _ngcontent-umy-c112=\"\">Akzeptierte Zahlungsmöglichkeiten</strong> - Vorkasse per Überweisung <br _ngcontent-umy-c112=\"\">" +
                " - Zahlung per PayPal <br _ngcontent-umy-c112=\"\"> - Zahlung per Kreditkarte <br _ngcontent-umy-c112=\"\"> - Zahlung auf Rechnung <br _ngcontent-umy-c112=\"\"><span _ngcontent-umy-c112=\"\">Bei Fragen finden Sie unsere Kontaktdaten im Impressum.</span></p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs6\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 6 Rücksendekosten</h3><p _ngcontent-umy-c112=\"\">Die Rücksendekosten übernehmen wir für Deutschland. Dies gilt nicht für unfrei verschickte Rücksendungen. Die Kostenrückerstattung erfolgt per Banküberweisung oder Gutschrift.</p><p _ngcontent-umy-c112=\"\">Rücksendungen aus anderen europäischen Ländern gehen zu Lasten des Versenders. Eine Lieferung ins außereuropäische Ausland erfolgt nicht bzw. nur nach schriftlichem Angebot.</p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs7\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 7 Zahlungs- und Lieferbedingungen</h3><p _ngcontent-umy-c112=\"\">Sofern nicht anders vereinbart, erfolgt die Lieferung ab Lager an die vom Besteller angegebene Lieferadresse.</p><p _ngcontent-umy-c112=\"\">" +
                "Der Besteller kann den Kaufpreis in Deutschland und Österreich mittels Überweisung zahlen. </p><p _ngcontent-umy-c112=\"\">Die Lieferzeit in Deutschland beträgt für verfügbare Lagerartikel 5 Arbeitstage nach Eingang Ihrer Bestellung. Nicht im Lager verfügbare Artikel werden 5 Arbeitstage nach Erscheinen geliefert. Informationen zu Lieferungen ins Ausland können während der üblichen Bürozeiten Im Verlag erfragt werden.</p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs8\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 8 Eigentumsvorbehalt</h3><p _ngcontent-umy-c112=\"\">Bis zur vollständigen Erfüllung der Kaufpreisforderung durch den Besteller verbleibt die gelieferte Ware im Eigentum des Verkäufers.</p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs9\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 9 Gewährleistung</h3><p _ngcontent-umy-c112=\"\">Liegt ein Mangel der Kaufsache vor, gelten die gesetzlichen Gewährleistungsvorschriften der §§ 434 ff. BGB.<br _ngcontent-umy-c112=\"\">" +
                " Zeigt sich ein Mangel innerhalb eines Jahres ab Ablieferung der Sache, können die Mängelansprüche im Rahmen der gesetzlichen Verjährungsfrist von zwei Jahren ab Ablieferung der Sache geltend gemacht werden. Die vorstehende Einschränkung gilt nicht:<br _ngcontent-umy-c112=\"\"> - für uns zurechenbare schuldhaft verursachte Schäden aus der Verletzung des Lebens, des Körpers oder der Gesundheit und bei vorsätzlich oder grob fahrlässig verursachten sonstigen Schäden;<br _ngcontent-umy-c112=\"\"> - soweit wir den Mangel arglistig verschwiegen oder eine Garantie für die Beschaffenheit der Sache übernommen haben.<br _ngcontent-umy-c112=\"\"><br _ngcontent-umy-c112=\"\"> Als Verbraucher werden Sie gebeten, die Sache bei Lieferung umgehend auf Vollständigkeit, offensichtliche Mängel und Transportschäden zu überprüfen und uns sowie dem Spediteur Beanstandungen schnellstmöglich mitzuteilen. Kommen Sie dem nicht nach, hat dies jedoch keine Auswirkung auf Ihre gesetzlichen Gewährleistungsansprüche.<br _ngcontent-umy-c112=\"\"><br _ngcontent-umy-c112=\"\"> Soweit Sie Unternehmer sind, gilt abweichend von den vorstehenden Gewährleistungsregelungen:<br _ngcontent-umy-c112=\"\"><br _ngcontent-umy-c112=\"\">" +
                "<b _ngcontent-umy-c112=\"\"> a) </b> Als Beschaffenheit der Sache gelten nur unsere eigenen Angaben und die Produktbeschreibung des Herstellers als vereinbart, nicht jedoch sonstige Werbung, öffentliche Anpreisungen und Äußerungen des Herstellers.<br _ngcontent-umy-c112=\"\"><br _ngcontent-umy-c112=\"\"><b _ngcontent-umy-c112=\"\">b)</b> Bei Mängeln leisten wir nach unserer Wahl Gewähr durch Nachbesserung oder Nachlieferung. Schlägt die Mangelbeseitigung fehl, können Sie nach Ihrer Wahl Minderung verlangen oder vom Vertrag zurücktreten. Die Mängelbeseitigung gilt nach erfolglosem zweiten Versuch als fehlgeschlagen, wenn sich nicht insbesondere aus der Art der Sache oder des Mangels oder den sonstigen Umständen etwas anderes ergibt. Im Falle der Nachbesserung müssen wir nicht die erhöhten Kosten tragen, die durch die Verbringung der Ware an einen anderen Ort als den Erfüllungsort entstehen, sofern die Verbringung nicht dem bestimmungsgemäßen Gebrauch der Ware entspricht.<br _ngcontent-umy-c112=\"\"><br _ngcontent-umy-c112=\"\"><b _ngcontent-umy-c112=\"\">c)</b> Die Gewährleistungsfrist beträgt ein Jahr ab Ablieferung der Ware. Die Fristverkürzung gilt nicht:<br _ngcontent-umy-c112=\"\">" +
                "<br _ngcontent-umy-c112=\"\"> - für uns zurechenbare schuldhaft verursachte Schäden aus der Verletzung des Lebens, des Körpers oder der Gesundheit und bei vorsätzlich oder grob fahrlässig verursachten sonstigen Schäden; - soweit wir den Mangel arglistig verschwiegen oder eine Garantie für die Beschaffenheit der Sache übernommen haben;<br _ngcontent-umy-c112=\"\"> - bei Sachen, die entsprechend ihrer üblichen Verwendungsweise für ein Bauwerk verwendet worden sind und dessen Mangelhaftigkeit verursacht haben;<br _ngcontent-umy-c112=\"\"> - bei gesetzlichen Rückgriffsansprüchen, die Sie im Zusammenhang mit Mängelrechten gegen uns haben.<br _ngcontent-umy-c112=\"\"></p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs10\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 10 Datenschutz</h3><p _ngcontent-umy-c112=\"\">Wir nutzen Ihre personenbezogenen Daten ausschließlich für Zwecke rund um Ihre Bestellung, so z. B. für die Information zu Ihrem Bestellstatus und/oder Lieferstatus und für interne Kundenanalysen. Persönliche Daten werden selbstverständlich vertraulich behandelt und nicht an Dritte weitergegeben. Der Besteller stimmt der Erhebung, Verarbeitung und Nutzung der im Zusammenhang mit der Geschäftsbeziehung erhaltenen Daten ausdrücklich zu.</p>" +
                "<p _ngcontent-umy-c112=\"\">Der Besteller hat ein Recht auf Auskunft sowie ein Recht auf Berichtigung, Sperrung und Löschung seiner gespeicherten Daten.</p></div><div _ngcontent-umy-c112=\"\" class=\"col-12\"><h3 _ngcontent-umy-c112=\"\" id=\"abs11\" class=\"bt-border col-12 light m-0 py-2 t-14 t-bold text-green\">§ 11 Anwendbares Recht, Gerichtsstand bei Kaufleuten, Online-Streitbeilegung gemäß Art. 14 Abs. 1 ODR-Verordnung:</h3><p _ngcontent-umy-c112=\"\">Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Ist der Kunde Kaufmann oder juristische Person des öffentlichen Rechts, ist ausschließlicher Gerichtsstand für alle Streitigkeiten aus dem Vertragsverhältnis das für unseren Firmensitz Hilden zuständige Gericht.</p><p _ngcontent-umy-c112=\"\">Wir nehmen an einem Streitbeilegungsverfahren einer Verbraucherschlichtungsstelle teil. Die für uns zuständige Verbraucherschlichtungsstelle ist: <strong _ngcontent-umy-c112=\"\">Allgemeine Verbraucherschlichtungsstelle des Zentrums für Schlichtung e. V.</strong><br> Straßburger Str. 8 <br _ngcontent-umy-c112=\"\"> 77694 Kehl <br _ngcontent-umy-c112=\"\"> Telefon: +49 7851 79579 40 <br _ngcontent-umy-c112=\"\"><br><br>" +
                " Telefax: +49 7851 79579 41 <br _ngcontent-umy-c112=\"\"> Internet: <a _ngcontent-umy-c112=\"\" class=\"text-primary\">www.verbraucher-schlichter.de</a><br _ngcontent-umy-c112=\"\"> E-Mail: <a _ngcontent-umy-c112=\"\" href=\"mailto:mail@verbraucher-schlichter.de\" class=\"text-primary\"><u _ngcontent-umy-c112=\"\">mail@verbraucher-schlichter.de</u></a><br _ngcontent-umy-c112=\"\"></p><p _ngcontent-umy-c112=\"\">Stand 30.02.2020</p><p _ngcontent-umy-c112=\"\"> Becker Joest Volk Verlag GmbH &amp; Co. KG <br _ngcontent-umy-c112=\"\"> Bahnhofsallee 5 <br _ngcontent-umy-c112=\"\"> 40721 Hilden Deutschland <br _ngcontent-umy-c112=\"\"></p><p _ngcontent-umy-c112=\"\" class=\"mt-5\"> Inhaber: <br _ngcontent-umy-c112=\"\"> Ralf Joest, Andreas Grewe, Johanna Hänichen, Justyna Schwertner </p></div></div></div>";

        UiUtils.AppWebViewClients webViewClients = new UiUtils.AppWebViewClients(progressBar);
        webViewClients.shouldOverrideUrlLoading(webView, htmlString2);
        webView.setWebViewClient(webViewClients);
        webView.loadUrl(htmlString2);
    }

}