var gardifyBaseUrl = 'https://gardifybackend.sslbeta.de/';

export const environment = {
  production: true,
  VAPID_KEY: 'BDhYJhVQLL5aCJ0H0wO3vGq9DjKx_u8hOxEW3jiRlUyFaRTfE-gqNMhZ57LTJecHvtDEhbbrnRbPdOfa__4r1Wo',
  gardifyBaseUrl: gardifyBaseUrl,
  forecastURL: gardifyBaseUrl + 'api/WeatherAPI/',
  fcDailyURL: gardifyBaseUrl + 'api/WeatherAPI/',
  todosURL: gardifyBaseUrl + 'api/todoesAPI/',
  threadsURL: gardifyBaseUrl + 'api/forumapi/',
  newsURL: gardifyBaseUrl + 'api/newsentriesapi/',
  gardenURL: gardifyBaseUrl + 'api/gardenapi/',
  faqURL: gardifyBaseUrl + 'api/faqentriesapi/',
  plantIdSearchURL: gardifyBaseUrl + 'api/plantsearchapi/',
  searchURL: gardifyBaseUrl + 'api/plantsearchapi/',
  searchQueriesURL: gardifyBaseUrl + 'api/SearchQueryAPI/',
  scanURL: gardifyBaseUrl + 'api/plantsearchimageapi',
  scanHistoryURL: gardifyBaseUrl + 'api/plantsearchimageapi/history',
  newsletterURL: gardifyBaseUrl + 'api/newsletterapi',
  groupURL: gardifyBaseUrl + 'api/groupapi',
  familyURL: gardifyBaseUrl + 'api/plantsearchapi/families',
  tagCatsURL: gardifyBaseUrl + 'api/planttagsapi/cats',
  tagURL: gardifyBaseUrl + 'api/planttagsapi/',
  articleURL: gardifyBaseUrl + 'api/articlesapi/',
  userPlantsURL: gardifyBaseUrl + 'api/userplantsapi/',
  pointsURL: gardifyBaseUrl + 'api/pointsapi/',
  lexiconURL: gardifyBaseUrl + 'api/lexiconapi/',
  diaryURL: gardifyBaseUrl + 'api/diaryapi',
  devicesURL: gardifyBaseUrl + 'api/DeviceAPI/',
  searchSiblingURL: gardifyBaseUrl + 'api/plantsearchapi/findSiblingById/',
  shopCartURL: gardifyBaseUrl + 'api/shopcartapi/',
  loginURL: gardifyBaseUrl + 'api/AccountAPI/login',
  registerURL: gardifyBaseUrl + 'api/AccountAPI/register',
  userURL: gardifyBaseUrl + 'api/AccountAPI/',
  updateUserURL: gardifyBaseUrl + 'api/AccountAPI/update/',
  deleteUserURL: gardifyBaseUrl + 'api/AccountAPI/delete/',
  userListsURL: gardifyBaseUrl + 'api/UserListAPI/',
  userDevicesListsURL: gardifyBaseUrl + 'api/UserDevicesListAPI/',
  adminDevicesListURL: gardifyBaseUrl + 'api/AdminDeviceAPI/',
  warningUrl: gardifyBaseUrl + '/api/WarningAPI',
  gpBaseUrl: 'https://gardify.de/intern/',
  forgotUrl: 'https://gardifybackend.sslbeta.de/api/AccountAPI/forgot',
  resendconfEmailUrl: gardifyBaseUrl + 'api/AccountAPI/resendConfEmail',
  ecolistUrl: gardifyBaseUrl + 'api/gardenapi/',
  ordersUrl: gardifyBaseUrl + 'api/OrdersAPI/',
  eventsUrl: gardifyBaseUrl + 'api/EventsAPI/',
  plantDocURL: gardifyBaseUrl + 'api/PlantDocAPI/',
  videosURL: gardifyBaseUrl + 'api/VideosAPI/',
  statsURL: gardifyBaseUrl + 'api/statsAPI/',
  citiesURL: gardifyBaseUrl + 'api/citiesAPI/',
  plzURL: gardifyBaseUrl + 'api/citiesAPI/verifyPLZ',
  subscriptionURL: gardifyBaseUrl + 'api/SubscriptionAPI',
  adsense: {
    adClient: 'ca-pub-3562132666777902',
    show: true
 }
};
