//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardifyModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public System.Guid ApplicationID { get; set; }
        public string AplicationName { get; set; }
        public string ApplicationRootPath { get; set; }
        public string ApplicationDescription { get; set; }
    }
}
