//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GardifyModels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileToModule
    {
        public System.Guid ApplicationId { get; set; }
        public int FileToModuleID { get; set; }
        public int ModuleID { get; set; }
        public int FileID { get; set; }
        public Nullable<int> DetailID { get; set; }
        public string Legend { get; set; }
        public string Description { get; set; }
        public string AltText { get; set; }
        public string TextLong { get; set; }
        public string LinkFromPic { get; set; }
        public string LinkTitle { get; set; }
        public string LinkToPic { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> DestinationWidth { get; set; }
        public Nullable<int> DestinationWidthDetail { get; set; }
        public Nullable<int> DestinationWidthHeightModal { get; set; }
        public bool Editable { get; set; }
        public bool TestFile { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string InsertedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
        public string EditedBy { get; set; }
        public bool IsMainImg { get; set; }
    }
}
