# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GardifyIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GardifyIOS

pod "Alamofire"
pod "Alamofire-Synchronous"
pod "MultiSlider"
pod "Charts"
pod "youtube-ios-player-helper"
pod "ReachabilitySwift"
pod "FontBlaster"

end
